spring:
  profiles: prod
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/zigong?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: lichee
  redis:
    port: 6379
    host: 127.0.0.1
    password: meiquanredis

geopark:
  image:
    exchange:
      server: http://www.geopark.com/exchange/
      path: /Users/Lichee/soft/develop/application/images/exchange
    production:
      server: http://www.geopark.com/production/
      path: /Users/Lichee/soft/develop/application/images/production
