spring:
  profiles: dev
  datasource:
    url: jdbc:p6spy:mysql://172.16.254.16:3306/zigong?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 6818799516
  redis:
    port: 6379
    host: 172.16.254.16
    password: shop

geopark:
  image:
    exchange:
      server: http://www.geopark.com/exchange/
      path: C:/geopark/images/exchange
    production:
      server: http://www.geopark.com/production/
      path: C:/geopark/images/production
    geolandscape:
      server: http://www.geopark.com/geolandscape/
      path: C:/geopark/images/geolandscape
    humanlandscape:
      server: http://www.geopark.com/humanlandscape/
      path: C:/geopark/images/humanlandscape
    parktopic:
      server: http://www.geopark.com/parktopic/
      path: C:/geopark/images/parktopic
    scienceactivity:
      server: http://www.geopark.com/scienceactivity/
      path: C:/geopark/images/scienceactivity
    geospecimen:
      server: http://www.geopark.com/geospecimen/
      path: C:/geopark/images/geospecimen
    biospecimen:
      server: http://www.geopark.com/biospecimen/
      path: C:/geopark/images/biospecimen
    humenexhibit:
      server: http://www.geopark.com/humenexhibit/
      path: C:/geopark/images/humenexhibit
    displayboard:
      server: http://www.geopark.com/displayboard/
      path: C:/geopark/images/displayboard
    parkmeeting:
      server: http://www.geopark.com/parkmeeting/
      path: C:/geopark/images/parkmeeting
    exchangeexhibition:
      server: http://www.geopark.com/exchangeexhibition/
      path: C:/geopark/images/exchangeexhibition
    parkrelation:
      server: http://www.geopark.com/parkrelation/
      path: C:/geopark/images/parkrelation
    researchpaper:
      server: http://www.geopark.com/researchpaper/
      path: C:/geopark/images/researchpaper